


try{
  let a = 2 + b    
} catch(Error){

    console.log(Error)
    
} finally{
  console.log('Executou')
}

